name: app_mobile2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  device_preview: ^1.2.0
  get_it: ^8.0.3
  email_validator: ^3.0.0
  provider: ^6.1.0
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8
  firebase_storage: ^12.4.6
  image_picker: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  firebase_auth_web: ^5.14.3 # Importante para web
  firebase_storage_web: ^3.10.13 # Importante para web
  cloud_firestore_web: ^4.3.0 # Importante para web

flutter:
  uses-material-design: true
  assets:
  - assets/images/
