// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAglKcfXZvEKXLd9-DGsgNOd1qdrTOMaQ',
    appId: '1:786008933276:web:0a31ac7c696b2c6e33fe59',
    messagingSenderId: '786008933276',
    projectId: 'conexao-cidadania-4bec5',
    authDomain: 'conexao-cidadania-4bec5.firebaseapp.com',
    storageBucket: 'conexao-cidadania-4bec5.firebasestorage.app',
    measurementId: 'G-81B0FSG2DN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbjHsjdvhNJqDl3EtARaY5UeM7-Zc3-8Y',
    appId: '1:786008933276:android:78083f9288f9c98d33fe59',
    messagingSenderId: '786008933276',
    projectId: 'conexao-cidadania-4bec5',
    storageBucket: 'conexao-cidadania-4bec5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgmm2y7KqlKYKynSqX4XvKWvOo2AVNbEs',
    appId: '1:786008933276:ios:22a2e9b57afef3e733fe59',
    messagingSenderId: '786008933276',
    projectId: 'conexao-cidadania-4bec5',
    storageBucket: 'conexao-cidadania-4bec5.firebasestorage.app',
    iosBundleId: 'com.example.appMobile2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgmm2y7KqlKYKynSqX4XvKWvOo2AVNbEs',
    appId: '1:786008933276:ios:22a2e9b57afef3e733fe59',
    messagingSenderId: '786008933276',
    projectId: 'conexao-cidadania-4bec5',
    storageBucket: 'conexao-cidadania-4bec5.firebasestorage.app',
    iosBundleId: 'com.example.appMobile2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAglKcfXZvEKXLd9-DGsgNOd1qdrTOMaQ',
    appId: '1:786008933276:web:edc54afc1e6676d233fe59',
    messagingSenderId: '786008933276',
    projectId: 'conexao-cidadania-4bec5',
    authDomain: 'conexao-cidadania-4bec5.firebaseapp.com',
    storageBucket: 'conexao-cidadania-4bec5.firebasestorage.app',
    measurementId: 'G-P1J5F21T3Q',
  );

}